-- 브랜드
CREATE TABLE brands (
    brand_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    brand_name    VARCHAR2(100) NOT NULL
);

-- 매장
--  PK DATA TYPE 직접 넣거나 안 넣으면 자동생성
-- dummy에서 id 생성되는 문제 때문에, store_id를 GENERATED BY DEFAULT ON NULL AS IDENTITY로 변경
CREATE TABLE stores (
    store_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name               VARCHAR2(100) NOT NULL,
    category           VARCHAR2(50) NOT NULL,
    region             VARCHAR2(20),
    lat                NUMBER(9,6) NOT NULL,
    lng                NUMBER(9,6) NOT NULL,
    avg_delivery_eta_min    NUMBER
);

-- correction_factor (5단계 fallback)
CREATE TABLE correction_factors (
    factor_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    scope_type     VARCHAR2(10) NOT NULL CHECK (scope_type IN ('store','brand','category','global')),
    scope_id       NUMBER,
    scope_value    VARCHAR2(50),
    factor_value   NUMBER DEFAULT 1.0 NOT NULL,
    sample_count   NUMBER DEFAULT 0,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 고객
CREATE TABLE customers (
    customer_id    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    delivery_lat   NUMBER(9,6),
    delivery_lng   NUMBER(9,6),
    delivery_address VARCHAR2(200)
);

-- 라이더
CREATE TABLE riders (
    rider_id              VARCHAR2(20) PRIMARY KEY,
    name                  VARCHAR2(50),
    region                VARCHAR2(20),
    vehicle               VARCHAR2(20) DEFAULT 'MOTORCYCLE',
    status                 VARCHAR2(20) DEFAULT 'AVAILABLE',
    completed_order_count  NUMBER DEFAULT 0
);

-- 패키지 (묶음)
CREATE TABLE packages (
    package_id       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    package_type     VARCHAR2(20) DEFAULT 'BUNDLE',
    rider_id         VARCHAR2(20),
    status           VARCHAR2(20) DEFAULT 'MATCHING',
    bundle_size      NUMBER,
    score            NUMBER,
    package_revenue  NUMBER,
    hourly_revenue   NUMBER,
    order_ids        JSON,
    route_detail     JSON,
    score_detail     JSON,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    offered_at       TIMESTAMP,
    accepted_at      TIMESTAMP,
    completed_at     TIMESTAMP
);

-- 주문
CREATE TABLE orders (
    order_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id         NUMBER REFERENCES customers(customer_id),
    store_id            NUMBER REFERENCES stores(store_id),
    package_id          NUMBER REFERENCES packages(package_id),
    owner_cook_min      NUMBER,
    predicted_cook_min  NUMBER,
    menu_items          JSON,
    delivery_lat        NUMBER(9,6),
    delivery_lng        NUMBER(9,6),
    amount              NUMBER,
    delivery_fee        NUMBER,
    request_note         VARCHAR2(200),
    status                 VARCHAR2(20) DEFAULT 'NEW',
    created_at              TIMESTAMP DEFAULT SYSTIMESTAMP,
    predicted_ready_at       TIMESTAMP,
    vector_corrected_at       TIMESTAMP,
    actual_ready_at            TIMESTAMP,
    picked_up_at                 TIMESTAMP,
    delivered_at                   TIMESTAMP
);

-- 과거 케이스 임베딩 (Vector Search)
CREATE TABLE vector_cases (
    case_id                 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    store_id                NUMBER REFERENCES stores(store_id),
    weekday                 NUMBER,
    time_slot                VARCHAR2(20),
    concurrent_order_count   NUMBER,
    actual_cook_time          NUMBER,
    embedding                  VECTOR(1024, FLOAT32)
);

-- 설명 (LLM 생성)
CREATE TABLE explanations (
    explanation_id  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    package_id      NUMBER REFERENCES packages(package_id),
    consumer_text   CLOB,
    rider_text      CLOB,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- =====================================================================
-- 외래키 제약조건 추가
ALTER TABLE packages ADD CONSTRAINT fk_packages_rider
    FOREIGN KEY (rider_id) REFERENCES riders(rider_id);

ALTER TABLE orders ADD CONSTRAINT fk_orders_store
    FOREIGN KEY (store_id) REFERENCES stores(store_id);